apiVersion: v1
kind: Namespace
metadata:
  name: client-orion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: client-orion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: client-orion
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

