apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: srespace-orion
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nolet7/srespace_dr.git
    path: k8s/clients/orion
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: client-orion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

