name: Deploy Velero

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      EKS_CLUSTER: srespace-orion-eks
      GKE_CLUSTER: srespace-orion-gke
      GKE_PROJECT: copper-poet-468323-t7
      GKE_ZONE: us-central1

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Install Gitleaks
      - name: Install Gitleaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz
          tar -xzf gitleaks_8.24.3_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      # 3. Run Gitleaks scan (never fails pipeline)
      - name: Run Gitleaks Secret Scan
        run: |
          gitleaks detect --source . \
            --config .gitleaks.toml \
            --redact \
            --no-banner \
            --report-format sarif \
            --report-path gitleaks-results.sarif || true

      # 4. Upload Gitleaks report
      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results
          path: gitleaks-results.sarif

      # 5. Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 6. Configure GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.VELERO_GCP_KEY_JSON }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GKE_PROJECT }}

      # 7. Install Helm
      - name: Setup Helm
        uses: azure/setup-helm@v4

      # 7b. Add Velero Helm repo
      - name: Add Velero Helm Repo
        run: |
          helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts
          helm repo update

      # 8. Deploy Velero on EKS
      - name: Deploy Velero on EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER
          helm upgrade --install velero vmware-tanzu/velero \
            --namespace velero --create-namespace \
            -f helm/values-velero-eks.yaml \
            --set configuration.backupStorageLocation[0].name=s3-primary \
            --set configuration.backupStorageLocation[0].provider=aws \
            --set configuration.backupStorageLocation[0].bucket=srespace-orion-velero-prod \
            --set configuration.backupStorageLocation[0].config.region=$AWS_REGION \
            --set configuration.volumeSnapshotLocation[0].name=aws-default \
            --set configuration.volumeSnapshotLocation[0].provider=aws \
            --set serviceAccount.server.annotations."eks\.amazonaws\.com/role-arn"="${{ secrets.VELERO_EKS_ROLE_ARN }}"

      # 9. Deploy Velero on GKE
      - name: Deploy Velero on GKE
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT        
          echo '${{ secrets.VELERO_GCP_KEY_JSON }}' > velero-gcp-credentials.json
          kubectl create secret generic cloud-credentials \
            --namespace velero \
            --from-file=cloud=velero-gcp-credentials.json \
            --dry-run=client -o yaml | kubectl apply -f -

          helm upgrade --install velero vmware-tanzu/velero \
            --namespace velero --create-namespace \
            -f helm/values-velero-gke.yaml \
            --set initContainers[0].name=velero-plugin-for-gcp \
            --set initContainers[0].image=velero/velero-plugin-for-gcp:v1.12.2 \
            --set initContainers[0].volumeMounts[0].mountPath=/target \
            --set initContainers[0].volumeMounts[0].name=plugins \
            --set configuration.backupStorageLocation[0].name=gcs-dr \
            --set configuration.backupStorageLocation[0].provider=gcp \
            --set configuration.backupStorageLocation[0].bucket=srespace-orion-velero-dr \
            --set configuration.volumeSnapshotLocation[0].name=gcp-default \
            --set configuration.volumeSnapshotLocation[0].provider=gcp \
            --set serviceAccount.server.annotations."iam\.gke\.io/gcp-service-account"="${{ secrets.VELERO_GSA_EMAIL }}" \
            --set credentials.existingSecret=cloud-credentials

